apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gen3-gen3test
  namespace: argocd
spec:
  project: default
  sources:
    - path: helm/gen3
      repoURL: https://github.com/uc-cdis/gen3-helm
      targetRevision: master
      helm:
        releaseName: gen3
        valueFiles:
          - $values/gen3test/test.planx-pla.net/values.yaml
    - repoURL: 'https://github.com/emalinowski/gen3-gitops-repo-gen3test'
      targetRevision: main
      ref: values
  destination:
    server: "https://kubernetes.default.svc"
    namespace: default
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    - Replace=true
    automated:
      selfHeal: true
